// AUTO-GENERATED by scripts/generate-registry.mjs — do not edit directly.
// Run `npm run registry` to refresh.

import type { FeatureManifest } from "@/core/registry/types";
import { manifest as accountDataEntries } from "@/features/account-data-entries/manifest";
import { manifest as accountMergePreflight } from "@/features/account-merge-preflight/manifest";
import { manifest as accountSigners } from "@/features/account-signers/manifest";
import { manifest as accountSnapshotDiff } from "@/features/account-snapshot-diff/manifest";
import { manifest as activityTimeline } from "@/features/activity-timeline/manifest";
import { manifest as addressValidator } from "@/features/address-validator/manifest";
import { manifest as amountConverter } from "@/features/amount-converter/manifest";
import { manifest as anchorDiscovery } from "@/features/anchor-discovery/manifest";
import { manifest as assetFlagsInspector } from "@/features/asset-flags-inspector/manifest";
import { manifest as assetMetadata } from "@/features/asset-metadata/manifest";
import { manifest as assetStatistics } from "@/features/asset-statistics/manifest";
import { manifest as balanceViewer } from "@/features/balance-viewer/manifest";
import { manifest as batchAddressValidator } from "@/features/batch-address-validator/manifest";
import { manifest as claimableBalances } from "@/features/claimable-balances/manifest";
import { manifest as claimablePredicateBuilder } from "@/features/claimable-predicate-builder/manifest";
import { manifest as effectsTimeline } from "@/features/effects-timeline/manifest";
import { manifest as federationResolver } from "@/features/federation-resolver/manifest";
import { manifest as feeBumpInspector } from "@/features/fee-bump-inspector/manifest";
import { manifest as feeStats } from "@/features/fee-stats/manifest";
import { manifest as freighterConnect } from "@/features/freighter-connect/manifest";
import { manifest as hashCalculator } from "@/features/hash-calculator/manifest";
import { manifest as horizonHealth } from "@/features/horizon-health/manifest";
import { manifest as ledgerLookup } from "@/features/ledger-lookup/manifest";
import { manifest as ledgerRangePlanner } from "@/features/ledger-range-planner/manifest";
import { manifest as liquidityPoolCalculator } from "@/features/liquidity-pool-calculator/manifest";
import { manifest as liquidityPoolInspector } from "@/features/liquidity-pool-inspector/manifest";
import { manifest as manageDataCodec } from "@/features/manage-data-codec/manifest";
import { manifest as memoInspector } from "@/features/memo-inspector/manifest";
import { manifest as muxedAccountCodec } from "@/features/muxed-account-codec/manifest";
import { manifest as networkComparison } from "@/features/network-comparison/manifest";
import { manifest as operationBrowser } from "@/features/operation-browser/manifest";
import { manifest as operationSourceMap } from "@/features/operation-source-map/manifest";
import { manifest as orderbookViewer } from "@/features/orderbook-viewer/manifest";
import { manifest as pathPaymentInspector } from "@/features/path-payment-inspector/manifest";
import { manifest as paymentCsvPreflight } from "@/features/payment-csv-preflight/manifest";
import { manifest as paymentQr } from "@/features/payment-qr/manifest";
import { manifest as preconditionsExplainer } from "@/features/preconditions-explainer/manifest";
import { manifest as priceFractionLab } from "@/features/price-fraction-lab/manifest";
import { manifest as reserveCalculator } from "@/features/reserve-calculator/manifest";
import { manifest as resultCodeExplainer } from "@/features/result-code-explainer/manifest";
import { manifest as sep10Inspector } from "@/features/sep10-inspector/manifest";
import { manifest as sep7SignatureVerifier } from "@/features/sep7-signature-verifier/manifest";
import { manifest as sequenceInspector } from "@/features/sequence-inspector/manifest";
import { manifest as signatureVerifier } from "@/features/signature-verifier/manifest";
import { manifest as simulationExplainer } from "@/features/simulation-explainer/manifest";
import { manifest as sorobanDecoder } from "@/features/soroban-decoder/manifest";
import { manifest as sponsoredReserves } from "@/features/sponsored-reserves/manifest";
import { manifest as strkeyInspector } from "@/features/strkey-inspector/manifest";
import { manifest as testnetFaucet } from "@/features/testnet-faucet/manifest";
import { manifest as tomlValidator } from "@/features/toml-validator/manifest";
import { manifest as tradeAggregationViewer } from "@/features/trade-aggregation-viewer/manifest";
import { manifest as tradeHistory } from "@/features/trade-history/manifest";
import { manifest as transactionDecoder } from "@/features/transaction-decoder/manifest";
import { manifest as transactionEnvelopeDiff } from "@/features/transaction-envelope-diff/manifest";
import { manifest as transactionLookup } from "@/features/transaction-lookup/manifest";
import { manifest as transactionSizeAnalyzer } from "@/features/transaction-size-analyzer/manifest";
import { manifest as trustlineChecker } from "@/features/trustline-checker/manifest";
import { manifest as trustlineLimitPlanner } from "@/features/trustline-limit-planner/manifest";
import { manifest as xdrInspector } from "@/features/xdr-inspector/manifest";

export const generatedRegistrySchemaVersion = 1 as const;
export const generatedManifests: FeatureManifest[] = [
  accountDataEntries,
  accountMergePreflight,
  accountSigners,
  accountSnapshotDiff,
  activityTimeline,
  addressValidator,
  amountConverter,
  anchorDiscovery,
  assetFlagsInspector,
  assetMetadata,
  assetStatistics,
  balanceViewer,
  batchAddressValidator,
  claimableBalances,
  claimablePredicateBuilder,
  effectsTimeline,
  federationResolver,
  feeBumpInspector,
  feeStats,
  freighterConnect,
  hashCalculator,
  horizonHealth,
  ledgerLookup,
  ledgerRangePlanner,
  liquidityPoolCalculator,
  liquidityPoolInspector,
  manageDataCodec,
  memoInspector,
  muxedAccountCodec,
  networkComparison,
  operationBrowser,
  operationSourceMap,
  orderbookViewer,
  pathPaymentInspector,
  paymentCsvPreflight,
  paymentQr,
  preconditionsExplainer,
  priceFractionLab,
  reserveCalculator,
  resultCodeExplainer,
  sep10Inspector,
  sep7SignatureVerifier,
  sequenceInspector,
  signatureVerifier,
  simulationExplainer,
  sorobanDecoder,
  sponsoredReserves,
  strkeyInspector,
  testnetFaucet,
  tomlValidator,
  tradeAggregationViewer,
  tradeHistory,
  transactionDecoder,
  transactionEnvelopeDiff,
  transactionLookup,
  transactionSizeAnalyzer,
  trustlineChecker,
  trustlineLimitPlanner,
  xdrInspector
];
