// AUTO-GENERATED by scripts/generate-registry.mjs — do not edit directly.
// Run `npm run registry` to refresh.

import type { ComponentType } from "react";
import type { FeatureEntry } from "@/core/registry/types";
import { manifest as accountDataEntries } from "@/features/account-data-entries/manifest";
import { manifest as accountMergePreflight } from "@/features/account-merge-preflight/manifest";
import { manifest as accountSigners } from "@/features/account-signers/manifest";
import { manifest as accountSnapshotDiff } from "@/features/account-snapshot-diff/manifest";
import { manifest as activityTimeline } from "@/features/activity-timeline/manifest";
import { manifest as addressValidator } from "@/features/address-validator/manifest";
import { manifest as amountConverter } from "@/features/amount-converter/manifest";
import { manifest as anchorDiscovery } from "@/features/anchor-discovery/manifest";
import { manifest as assetFlagsInspector } from "@/features/asset-flags-inspector/manifest";
import { manifest as assetMetadata } from "@/features/asset-metadata/manifest";
import { manifest as assetStatistics } from "@/features/asset-statistics/manifest";
import { manifest as balanceViewer } from "@/features/balance-viewer/manifest";
import { manifest as batchAddressValidator } from "@/features/batch-address-validator/manifest";
import { manifest as claimableBalances } from "@/features/claimable-balances/manifest";
import { manifest as claimablePredicateBuilder } from "@/features/claimable-predicate-builder/manifest";
import { manifest as contractEvents } from "@/features/contract-events/manifest";
import { manifest as effectsTimeline } from "@/features/effects-timeline/manifest";
import { manifest as explorerLinks } from "@/features/explorer-links/manifest";
import { manifest as federationResolver } from "@/features/federation-resolver/manifest";
import { manifest as feeBumpInspector } from "@/features/fee-bump-inspector/manifest";
import { manifest as feeStats } from "@/features/fee-stats/manifest";
import { manifest as freighterConnect } from "@/features/freighter-connect/manifest";
import { manifest as hashCalculator } from "@/features/hash-calculator/manifest";
import { manifest as horizonHealth } from "@/features/horizon-health/manifest";
import { manifest as ledgerLookup } from "@/features/ledger-lookup/manifest";
import { manifest as ledgerRangePlanner } from "@/features/ledger-range-planner/manifest";
import { manifest as liquidityPoolCalculator } from "@/features/liquidity-pool-calculator/manifest";
import { manifest as liquidityPoolInspector } from "@/features/liquidity-pool-inspector/manifest";
import { manifest as manageDataCodec } from "@/features/manage-data-codec/manifest";
import { manifest as memoInspector } from "@/features/memo-inspector/manifest";
import { manifest as muxedAccountCodec } from "@/features/muxed-account-codec/manifest";
import { manifest as networkComparison } from "@/features/network-comparison/manifest";
import { manifest as operationBrowser } from "@/features/operation-browser/manifest";
import { manifest as operationSourceMap } from "@/features/operation-source-map/manifest";
import { manifest as orderbookViewer } from "@/features/orderbook-viewer/manifest";
import { manifest as pathPaymentFinder } from "@/features/path-payment-finder/manifest";
import { manifest as pathPaymentInspector } from "@/features/path-payment-inspector/manifest";
import { manifest as paymentCsvPreflight } from "@/features/payment-csv-preflight/manifest";
import { manifest as paymentHistory } from "@/features/payment-history/manifest";
import { manifest as paymentQr } from "@/features/payment-qr/manifest";
import { manifest as paymentUriParser } from "@/features/payment-uri-parser/manifest";
import { manifest as preconditionsExplainer } from "@/features/preconditions-explainer/manifest";
import { manifest as priceFractionLab } from "@/features/price-fraction-lab/manifest";
import { manifest as reserveCalculator } from "@/features/reserve-calculator/manifest";
import { manifest as resultCodeExplainer } from "@/features/result-code-explainer/manifest";
import { manifest as sep10Inspector } from "@/features/sep10-inspector/manifest";
import { manifest as sep7SignatureVerifier } from "@/features/sep7-signature-verifier/manifest";
import { manifest as sequenceInspector } from "@/features/sequence-inspector/manifest";
import { manifest as signatureVerifier } from "@/features/signature-verifier/manifest";
import { manifest as simulationExplainer } from "@/features/simulation-explainer/manifest";
import { manifest as sorobanAuthInspector } from "@/features/soroban-auth-inspector/manifest";
import { manifest as sorobanDecoder } from "@/features/soroban-decoder/manifest";
import { manifest as sorobanFeeEstimator } from "@/features/soroban-fee-estimator/manifest";
import { manifest as sorobanSpecViewer } from "@/features/soroban-spec-viewer/manifest";
import { manifest as sponsoredReserves } from "@/features/sponsored-reserves/manifest";
import { manifest as strkeyInspector } from "@/features/strkey-inspector/manifest";
import { manifest as testnetFaucet } from "@/features/testnet-faucet/manifest";
import { manifest as tomlValidator } from "@/features/toml-validator/manifest";
import { manifest as tradeAggregationViewer } from "@/features/trade-aggregation-viewer/manifest";
import { manifest as tradeHistory } from "@/features/trade-history/manifest";
import { manifest as transactionDecoder } from "@/features/transaction-decoder/manifest";
import { manifest as transactionEnvelopeDiff } from "@/features/transaction-envelope-diff/manifest";
import { manifest as transactionLookup } from "@/features/transaction-lookup/manifest";
import { manifest as transactionSizeAnalyzer } from "@/features/transaction-size-analyzer/manifest";
import { manifest as trustlineChecker } from "@/features/trustline-checker/manifest";
import { manifest as trustlineLimitPlanner } from "@/features/trustline-limit-planner/manifest";
import { manifest as xdrInspector } from "@/features/xdr-inspector/manifest";

export const generatedRegistrySchemaVersion = 1 as const;
export const generatedFeatures: FeatureEntry[] = [
  { manifest: accountDataEntries, load: async () => { const mod = await import("@/features/account-data-entries/panel"); return mod.default as ComponentType; } },
  { manifest: accountMergePreflight, load: async () => { const mod = await import("@/features/account-merge-preflight/panel"); return mod.default as ComponentType; } },
  { manifest: accountSigners, load: async () => { const mod = await import("@/features/account-signers/panel"); return mod.default as ComponentType; } },
  { manifest: accountSnapshotDiff, load: async () => { const mod = await import("@/features/account-snapshot-diff/panel"); return mod.default as ComponentType; } },
  { manifest: activityTimeline, load: async () => { const mod = await import("@/features/activity-timeline/panel"); return mod.default as ComponentType; } },
  { manifest: addressValidator, load: async () => { const mod = await import("@/features/address-validator/panel"); return mod.default as ComponentType; } },
  { manifest: amountConverter, load: async () => { const mod = await import("@/features/amount-converter/panel"); return mod.default as ComponentType; } },
  { manifest: anchorDiscovery, load: async () => { const mod = await import("@/features/anchor-discovery/panel"); return mod.default as ComponentType; } },
  { manifest: assetFlagsInspector, load: async () => { const mod = await import("@/features/asset-flags-inspector/panel"); return mod.default as ComponentType; } },
  { manifest: assetMetadata, load: async () => { const mod = await import("@/features/asset-metadata/panel"); return mod.default as ComponentType; } },
  { manifest: assetStatistics, load: async () => { const mod = await import("@/features/asset-statistics/panel"); return mod.default as ComponentType; } },
  { manifest: balanceViewer, load: async () => { const mod = await import("@/features/balance-viewer/panel"); return mod.default as ComponentType; } },
  { manifest: batchAddressValidator, load: async () => { const mod = await import("@/features/batch-address-validator/panel"); return mod.default as ComponentType; } },
  { manifest: claimableBalances, load: async () => { const mod = await import("@/features/claimable-balances/panel"); return mod.default as ComponentType; } },
  { manifest: claimablePredicateBuilder, load: async () => { const mod = await import("@/features/claimable-predicate-builder/panel"); return mod.default as ComponentType; } },
  { manifest: contractEvents, load: async () => { const mod = await import("@/features/contract-events/panel"); return mod.default as ComponentType; } },
  { manifest: effectsTimeline, load: async () => { const mod = await import("@/features/effects-timeline/panel"); return mod.default as ComponentType; } },
  { manifest: explorerLinks, load: async () => { const mod = await import("@/features/explorer-links/panel"); return mod.default as ComponentType; } },
  { manifest: federationResolver, load: async () => { const mod = await import("@/features/federation-resolver/panel"); return mod.default as ComponentType; } },
  { manifest: feeBumpInspector, load: async () => { const mod = await import("@/features/fee-bump-inspector/panel"); return mod.default as ComponentType; } },
  { manifest: feeStats, load: async () => { const mod = await import("@/features/fee-stats/panel"); return mod.default as ComponentType; } },
  { manifest: freighterConnect, load: async () => { const mod = await import("@/features/freighter-connect/panel"); return mod.default as ComponentType; } },
  { manifest: hashCalculator, load: async () => { const mod = await import("@/features/hash-calculator/panel"); return mod.default as ComponentType; } },
  { manifest: horizonHealth, load: async () => { const mod = await import("@/features/horizon-health/panel"); return mod.default as ComponentType; } },
  { manifest: ledgerLookup, load: async () => { const mod = await import("@/features/ledger-lookup/panel"); return mod.default as ComponentType; } },
  { manifest: ledgerRangePlanner, load: async () => { const mod = await import("@/features/ledger-range-planner/panel"); return mod.default as ComponentType; } },
  { manifest: liquidityPoolCalculator, load: async () => { const mod = await import("@/features/liquidity-pool-calculator/panel"); return mod.default as ComponentType; } },
  { manifest: liquidityPoolInspector, load: async () => { const mod = await import("@/features/liquidity-pool-inspector/panel"); return mod.default as ComponentType; } },
  { manifest: manageDataCodec, load: async () => { const mod = await import("@/features/manage-data-codec/panel"); return mod.default as ComponentType; } },
  { manifest: memoInspector, load: async () => { const mod = await import("@/features/memo-inspector/panel"); return mod.default as ComponentType; } },
  { manifest: muxedAccountCodec, load: async () => { const mod = await import("@/features/muxed-account-codec/panel"); return mod.default as ComponentType; } },
  { manifest: networkComparison, load: async () => { const mod = await import("@/features/network-comparison/panel"); return mod.default as ComponentType; } },
  { manifest: operationBrowser, load: async () => { const mod = await import("@/features/operation-browser/panel"); return mod.default as ComponentType; } },
  { manifest: operationSourceMap, load: async () => { const mod = await import("@/features/operation-source-map/panel"); return mod.default as ComponentType; } },
  { manifest: orderbookViewer, load: async () => { const mod = await import("@/features/orderbook-viewer/panel"); return mod.default as ComponentType; } },
  { manifest: pathPaymentFinder, load: async () => { const mod = await import("@/features/path-payment-finder/panel"); return mod.default as ComponentType; } },
  { manifest: pathPaymentInspector, load: async () => { const mod = await import("@/features/path-payment-inspector/panel"); return mod.default as ComponentType; } },
  { manifest: paymentCsvPreflight, load: async () => { const mod = await import("@/features/payment-csv-preflight/panel"); return mod.default as ComponentType; } },
  { manifest: paymentHistory, load: async () => { const mod = await import("@/features/payment-history/panel"); return mod.default as ComponentType; } },
  { manifest: paymentQr, load: async () => { const mod = await import("@/features/payment-qr/panel"); return mod.default as ComponentType; } },
  { manifest: paymentUriParser, load: async () => { const mod = await import("@/features/payment-uri-parser/panel"); return mod.default as ComponentType; } },
  { manifest: preconditionsExplainer, load: async () => { const mod = await import("@/features/preconditions-explainer/panel"); return mod.default as ComponentType; } },
  { manifest: priceFractionLab, load: async () => { const mod = await import("@/features/price-fraction-lab/panel"); return mod.default as ComponentType; } },
  { manifest: reserveCalculator, load: async () => { const mod = await import("@/features/reserve-calculator/panel"); return mod.default as ComponentType; } },
  { manifest: resultCodeExplainer, load: async () => { const mod = await import("@/features/result-code-explainer/panel"); return mod.default as ComponentType; } },
  { manifest: sep10Inspector, load: async () => { const mod = await import("@/features/sep10-inspector/panel"); return mod.default as ComponentType; } },
  { manifest: sep7SignatureVerifier, load: async () => { const mod = await import("@/features/sep7-signature-verifier/panel"); return mod.default as ComponentType; } },
  { manifest: sequenceInspector, load: async () => { const mod = await import("@/features/sequence-inspector/panel"); return mod.default as ComponentType; } },
  { manifest: signatureVerifier, load: async () => { const mod = await import("@/features/signature-verifier/panel"); return mod.default as ComponentType; } },
  { manifest: simulationExplainer, load: async () => { const mod = await import("@/features/simulation-explainer/panel"); return mod.default as ComponentType; } },
  { manifest: sorobanAuthInspector, load: async () => { const mod = await import("@/features/soroban-auth-inspector/panel"); return mod.default as ComponentType; } },
  { manifest: sorobanDecoder, load: async () => { const mod = await import("@/features/soroban-decoder/panel"); return mod.default as ComponentType; } },
  { manifest: sorobanFeeEstimator, load: async () => { const mod = await import("@/features/soroban-fee-estimator/panel"); return mod.default as ComponentType; } },
  { manifest: sorobanSpecViewer, load: async () => { const mod = await import("@/features/soroban-spec-viewer/panel"); return mod.default as ComponentType; } },
  { manifest: sponsoredReserves, load: async () => { const mod = await import("@/features/sponsored-reserves/panel"); return mod.default as ComponentType; } },
  { manifest: strkeyInspector, load: async () => { const mod = await import("@/features/strkey-inspector/panel"); return mod.default as ComponentType; } },
  { manifest: testnetFaucet, load: async () => { const mod = await import("@/features/testnet-faucet/panel"); return mod.default as ComponentType; } },
  { manifest: tomlValidator, load: async () => { const mod = await import("@/features/toml-validator/panel"); return mod.default as ComponentType; } },
  { manifest: tradeAggregationViewer, load: async () => { const mod = await import("@/features/trade-aggregation-viewer/panel"); return mod.default as ComponentType; } },
  { manifest: tradeHistory, load: async () => { const mod = await import("@/features/trade-history/panel"); return mod.default as ComponentType; } },
  { manifest: transactionDecoder, load: async () => { const mod = await import("@/features/transaction-decoder/panel"); return mod.default as ComponentType; } },
  { manifest: transactionEnvelopeDiff, load: async () => { const mod = await import("@/features/transaction-envelope-diff/panel"); return mod.default as ComponentType; } },
  { manifest: transactionLookup, load: async () => { const mod = await import("@/features/transaction-lookup/panel"); return mod.default as ComponentType; } },
  { manifest: transactionSizeAnalyzer, load: async () => { const mod = await import("@/features/transaction-size-analyzer/panel"); return mod.default as ComponentType; } },
  { manifest: trustlineChecker, load: async () => { const mod = await import("@/features/trustline-checker/panel"); return mod.default as ComponentType; } },
  { manifest: trustlineLimitPlanner, load: async () => { const mod = await import("@/features/trustline-limit-planner/panel"); return mod.default as ComponentType; } },
  { manifest: xdrInspector, load: async () => { const mod = await import("@/features/xdr-inspector/panel"); return mod.default as ComponentType; } }
];
