import { it } from "vitest";
import { renderFeature, screen } from "@/core/testing/render";
import { expectNoAxeViolations } from "@/core/testing/axe";
import { withMswHandlers } from "@/core/testing/msw";
import { resetHorizonClients } from "@/core/horizon/client";
import { handlers } from "../msw/handlers";
import { LedgerLookupPanel } from "../components/LedgerLookupPanel";
import { copy } from "../copy";
withMswHandlers(...handlers);
it("has no WCAG violations initially", async () => {const {container} = renderFeature(<LedgerLookupPanel/>);await expectNoAxeViolations(container);});
it("has no WCAG violations with a ledger", async () => {resetHorizonClients();const {container,user} = renderFeature(<LedgerLookupPanel/>); await user.type(screen.getByLabelText(copy.formLabel),"900"); await user.click(screen.getByRole("button",{name:copy.submit})); await screen.findByText("900,719,925.4740993"); await expectNoAxeViolations(container);});
